CREATE TABLE trader(
	TraderID VARCHAR(50) PRIMARY KEY,
	TraderName VARCHAR(255) NOT NULL,
	Address TEXT NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Email VARCHAR(255) UNIQUE NOT NULL,
	Tin VARCHAR(50) UNIQUE NOT NULL,
	TraderType VARCHAR(50) NOT NULL
);
