- Generated by the database client.
CREATE TABLE shipment(
    shipmentid varchar(255) NOT NULL,
    goodid varchar(255) NOT NULL,
    portid varchar(255) NOT NULL,
    traderid varchar(255) NOT NULL,
    shipmentdate date NOT NULL,
    direction varchar(255),
    status varchar(255),
    PRIMARY KEY(shipmentid),
    CONSTRAINT shipment_goodid_fkey FOREIGN key(goodid) REFERENCES good(goodid),
    CONSTRAINT shipment_portid_fkey FOREIGN key(portid) REFERENCES port(portid),
    CONSTRAINT shipment_traderid_fkey FOREIGN key(traderid) REFERENCES trader(traderid),
    CONSTRAINT shipment_direction_check CHECK ((direction)::text = ANY ((ARRAY['IMPORT'::character varying, 'EXPORT'::character varying])::text[])),
    CONSTRAINT shipment_status_check CHECK ((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_TRANSIT'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[]))
);
CREATE INDEX idx_shipment_status ON public.shipment USING btree (status);
CREATE INDEX idx_shipment_direction ON public.shipment USING btree (direction);
CREATE INDEX idx_shipment_date ON public.shipment USING btree (shipmentdate);
CREATE INDEX idx_shipment_goodid ON public.shipment USING btree (goodid);
CREATE INDEX idx_shipment_portid ON public.shipment USING btree (portid);
CREATE INDEX idx_shipment_traderid ON public.shipment U